# -*- coding: utf-8 -*-
"""Mistral_ChatBot_v2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1B2rK77R6Rol1BGqDaz3b5TiiL9SmHWxk
"""

!pip install -q -U bitsandbytes>=0.46.1

import bitsandbytes
print(bitsandbytes.__version__)

!pip install -q -U transformers
!pip install -q -U accelerate

'''from transformers import AutoTokenizer, AutoModelForCausalLM,BitsAndBytesConfig,pipeline
import torch

bnb_config=BitsAndBytesConfig(
    load_in_4bit=True,
    bnb_4bit_quant_type='nf4',
    bnb_4bit_use_double_quant=True,

)'''

from transformers import AutoTokenizer, AutoModelForCausalLM, BitsAndBytesConfig, pipeline
import torch

bnb_config = BitsAndBytesConfig(
    load_in_4bit=True,
    bnb_4bit_quant_type="nf4",
    bnb_4bit_use_double_quant=True,
)

from huggingface_hub import login
login()

'''model_name="mistralai/Mistral-7B-v0.1"
tokenizer=AutoTokenizer.from_pretrained(model_name)
model=AutoModelForCausalLM.from_pretrained(
  model_name,
  quantization_config=bnb_config,
  torch_dtype=torch.bfloat16,
  device_map='auto',
  trust_remote_code=True,
)'''

model_name = "mistralai/Mistral-7B-v0.1"

tokenizer = AutoTokenizer.from_pretrained(model_name)
model = AutoModelForCausalLM.from_pretrained(
        model_name,
        quantization_config=bnb_config,
        torch_dtype=torch.bfloat16,
        device_map="auto",
        trust_remote_code=True,
    )

pipe=pipeline(
    'text-generation',
    model=model,
    tokenizer=tokenizer,
    torch_dtype=torch.bfloat16,
    device_map='auto'
)

def get_response(prompt):
    sequences = pipe(
        prompt,
        do_sample=False,
        max_new_tokens=50,
        temperature=0.8,
        top_k=50,
        top_p=0.95,
        num_return_sequences=1,
        return_full_text=False, # 1. Only return the new response
        eos_token_id=pipe.tokenizer.eos_token_id, # 2. Stop at End-Of-Sentence
    )

    generated_text = sequences[0]['generated_text']

    # 3. Clean up: Split by "###" to prevent the model from
    # hallucinating future user/system turns
    clean_response = generated_text.split("###")[0].strip()
    return clean_response

def chatbot():
    system_prompt = "You are a helpful assistant."
    conversation_history = []

    while True:
        print("\nEnter quit/bye/exit to leave...")
        user_input = input("User: ")

        if user_input.lower() in ["quit", "bye", "exit", "good bye", "goodbye"]:
            break

        # Construct prompt
        full_prompt_parts = [f"### System: {system_prompt}\n"]
        for turn in conversation_history:
            full_prompt_parts.append(f"### User: {turn['user']}\n### Assistant: {turn['assistant']}\n")

        full_prompt_parts.append(f"### User: {user_input}\n### Assistant:")
        input_prompt = "".join(full_prompt_parts)

        response = get_response(input_prompt)
        print("Bot:", response)

        # 4. CRITICAL: Save the turn to memory so history actually works
        conversation_history.append({"user": user_input, "assistant": response})

chatbot()